spring:
  application:
    name: userpost
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver: org.postgresql.Driver
  liquibase:
    parameters:
      charSet: UTF-8
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.liquibase: INFO
    com.airplane: DEBUG

  file:
    name: logs/userposts.log
    max-size: 10MB
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"